name: Build Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: ~/.m2
          key: maven
          restore-keys: maven
      - name: Dependency
        run: |
          wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
          tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C phantomjs
      - name: Build
        run: |
          curl -L https://github.com/jenkins-zh/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv
          export PATH=.:$PATH:phantomjs/bin
          jcli cwp --config-path formula.yaml
      - name: Push Image
          docker login --username ${{ secrets.DOCKER_HUB_USER }} --password ${{secrets.DOCKER_HUB_TOKEN}}
          docker push surenpi/test:ks-jenkins
